export const UI_TEXT = {
  common: {
    loadingAriaLabel: 'Loading'
  },
  myDecks: {
    workspaceLabel: 'Workspace',
    title: 'My Decks',
    subtitle: 'Organize public decks and your private study sets.',
    newDeck: 'New deck',
    sortLabel: 'Sort',
    sortAriaLabel: 'Sort decks',
    sortOptions: {
      newest: 'Newest',
      oldest: 'Oldest',
      difficultyHigh: 'Difficulty: High -> Low',
      difficultyLow: 'Difficulty: Low -> High'
    },
    publicTitle: 'Public decks',
    publicSubtitle: 'Visible to everyone.',
    privateTitle: 'Private decks',
    privateSubtitle: 'Only visible to you.',
    totalLabel: 'total',
    publicBadge: 'Public',
    privateBadge: 'Private',
    cardsLabel: 'cards',
    play: 'Play',
    edit: 'Edit',
    delete: 'Delete',
    noPublicDecks: 'No public decks yet.',
    noPrivateDecks: 'No private decks yet.',
    noCardsTitle: 'No cards yet',
    noCardsBodySuffix: 'has 0 cards. Add cards first to start practice.',
    close: 'Close',
    addCards: 'Add cards',
    deleteDeckTitle: 'Delete deck?',
    deleteDeckConfirmPrefix: 'Are you sure you want to delete "',
    deleteDeckConfirmSuffix: '"?',
    cancel: 'Cancel'
  },
  deckDetail: {
    backToDecks: 'Back to decks',
    manageTitle: 'Manage deck',
    cardsLabel: 'cards',
    newCard: 'New card',
    detailsTitle: 'Deck details',
    detailsSubtitle: 'Edit deck info and keep cards updated.',
    settingsBadge: 'Settings',
    nameLabel: 'Name',
    namePlaceholder: 'Deck name',
    publicLabel: 'Public deck',
    saving: 'Saving...',
    saveChanges: 'Save changes',
    filterLabel: 'Filter',
    filterAll: 'All',
    generalTag: 'General',
    difficultyLabel: 'Difficulty:',
    edit: 'Edit',
    delete: 'Delete',
    emptyCards: 'No cards yet. Add your first card.',
    deleteCardTitle: 'Delete card?',
    deleteCardConfirmPrefix: 'Are you sure you want to delete "',
    deleteCardConfirmSuffix: '"?',
    cancel: 'Cancel'
  },
  deckPractice: {
    practiceLabel: 'Practice',
    fallbackDeckName: 'Deck',
    cardsLabel: 'cards',
    publicLabel: 'Public',
    privateLabel: 'Private',
    backToDecks: 'Back to decks',
    randomOrderOn: 'Random order: On',
    randomOrderOff: 'Random order: Off',
    shuffle: 'Shuffle',
    tagLabel: 'Tag',
    tagAriaLabel: 'Filter by tag',
    allTags: 'All tags',
    generalTag: 'General',
    difficultyLabel: 'Difficulty',
    difficultyAriaLabel: 'Filter by difficulty',
    difficultyAll: 'All',
    difficultyLow: 'Low',
    difficultyMedium: 'Medium',
    difficultyHard: 'Hard',
    countLabel: 'cards',
    cardLabel: 'Card',
    answerLabel: 'Answer',
    tapToFlip: 'Tap show answer to flip.',
    showAnswer: 'Show answer',
    hideAnswer: 'Hide answer',
    prev: 'Prev',
    next: 'Next',
    restart: 'Restart',
    emptyDeck: 'No cards in this deck yet.',
    noMatches: 'No cards match the selected filters.'
  },
  quickLearn: {
    label: 'Quick learn',
    backToDeck: 'Back to deck',
    startOver: 'Start over',
    showAnswer: 'Show answer',
    hideAnswer: 'Hide answer',
    correct: 'Correct',
    incorrect: 'Incorrect',
    submit: 'Submit results',
    noCards: 'No cards available for quick learn.',
    sessionStats: 'Session stats',
    deckStats: 'Deck stats',
    totalCards: 'Total cards',
    correctCount: 'Correct',
    incorrectCount: 'Incorrect',
    accuracy: 'Accuracy',
    cardsStudied: 'Cards studied',
    overallAccuracy: 'Overall accuracy',
  },
  home: {
    sectionLabel: 'Public decks',
    title: 'Learn from community collections',
    subtitle: 'Pick a deck by topic, size, or card count and start learning.',
    searchPlaceholder: 'Search by deck name',
    reset: 'Reset',
    sortLabel: 'Sort',
    sortOptions: {
      newest: 'Newest',
      oldest: 'Oldest',
      mostCards: 'Most cards',
      leastCards: 'Least cards',
      nameAZ: 'Name A–Z',
      nameZA: 'Name Z–A'
    },
    sizeLabel: 'Deck size',
    sizeOptions: {
      all: 'All decks',
      small: 'Small (1 - 20)',
      medium: 'Medium (21 - 60)',
      large: 'Large (61+)',
      empty: 'Empty (0)'
    },
    minCardsLabel: 'Minimum cards',
    minCardsPlaceholder: 'e.g. 10',
    showingPrefix: 'Showing',
    showingMiddle: 'of',
    showingSuffix: 'decks',
    activeFilters: 'Active filters',
    nameFilterPrefix: 'Name:',
    sizeFilterPrefix: 'Size:',
    minCardsFilterPrefix: 'Min cards:',
    errorMessage: 'We could not load public decks right now. Please try again.',
    retry: 'Try again',
    emptyTitle: 'No decks to show',
    emptyBody: 'Try changing filters or resetting the search.',
    resetFilters: 'Reset filters',
    createdLabel: 'Created',
    cardsLabel: 'cards',
    emptyDeckLabel: 'Empty deck',
    readyLabel: 'Ready to learn',
    publicBadge: 'Public',
    play: 'Play',
    sizeLabels: {
      all: 'All',
      small: 'Small',
      medium: 'Medium',
      large: 'Large',
      empty: 'Empty'
    }
  }
} as const;
